-- ⚠️  DO NOT RUN THIS FILE. It is kept only so old links and notes still resolve.
--
-- The canonical one-row-per-swimmer schema is:
--
--     supabase/migrations/0010_vx_roster.sql
--
-- Run THAT one. It is what the app writes to and what the app names when it asks for the table
-- to be created ("Run supabase/migrations/0010_vx_roster.sql").
--
-- Why this file is disarmed
-- -------------------------
-- An earlier draft of the rows table lived here with a different shape: a single `state` column
-- holding 'edit' / 'added' / 'deleted'. The app never shipped against that shape. It writes two
-- booleans instead — `added` and `deleted` — because a swimmer can be both at once mid-move, and
-- a row read back has to say which without a second lookup. Creating the table from the old shape
-- here, and then letting the app write `added`/`deleted` to it, is exactly the kind of schema
-- mismatch that has cost this club its roster before: every row write would fail against columns
-- that do not exist, silently, one swimmer at a time.
--
-- Two files creating the SAME table name with DIFFERENT columns is a trap with no upside, so the
-- DDL is removed from this one and there is now a single source of truth.
--
-- The rationale for rows over one document is unchanged and worth keeping:
--
--   Every addition, edit and removal the club made used to live in ONE club_state document
--   (vx_roster_edits). The last device to write anything replaced every other device's work,
--   silently — which is how 304 swimmers became 317 overnight. A row keyed on squad AND swimmer
--   ("junior::sw_12") means Sameh editing a Junior and Mary editing a Senior A write different
--   rows and cannot overwrite each other. A move is a removal from one squad and an addition to
--   another, so both halves exist at once — which is why the key carries the squad, not only the
--   swimmer, and why the row carries `deleted` and `added` rather than a single state.
--
-- To check the live club (read-only), the columns that actually exist are added/deleted:
--   select added, deleted, count(*) from vx_roster group by 1, 2;
--   select squad_id, count(*) from vx_roster where deleted group by squad_id;
